/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecursRouteImport } from './routes/recurs'
import { Route as XerradesRouteImport } from './routes/xerrades'
import { Route as RetirRouteImport } from './routes/retir'
import { Route as MareFillaRouteImport } from './routes/mare-filla'
import { Route as MatriusRouteImport } from './routes/matrius'
import { Route as IndividualRouteImport } from './routes/individual'
import { Route as CuresRouteImport } from './routes/cures'
import { Route as IndexRouteImport } from './routes/index'

const RecursRoute = RecursRouteImport.update({
  id: '/recurs',
  path: '/recurs',
  getParentRoute: () => rootRouteImport,
} as any)
const XerradesRoute = XerradesRouteImport.update({
  id: '/xerrades',
  path: '/xerrades',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirRoute = RetirRouteImport.update({
  id: '/retir',
  path: '/retir',
  getParentRoute: () => rootRouteImport,
} as any)
const MareFillaRoute = MareFillaRouteImport.update({
  id: '/mare-filla',
  path: '/mare-filla',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriusRoute = MatriusRouteImport.update({
  id: '/matrius',
  path: '/matrius',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualRoute = IndividualRouteImport.update({
  id: '/individual',
  path: '/individual',
  getParentRoute: () => rootRouteImport,
} as any)
const CuresRoute = CuresRouteImport.update({
  id: '/cures',
  path: '/cures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cures': typeof CuresRoute
  '/individual': typeof IndividualRoute
  '/mare-filla': typeof MareFillaRoute
  '/matrius': typeof MatriusRoute
  '/recurs': typeof RecursRoute
  '/retir': typeof RetirRoute
  '/xerrades': typeof XerradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cures': typeof CuresRoute
  '/individual': typeof IndividualRoute
  '/mare-filla': typeof MareFillaRoute
  '/matrius': typeof MatriusRoute
  '/recurs': typeof RecursRoute
  '/retir': typeof RetirRoute
  '/xerrades': typeof XerradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cures': typeof CuresRoute
  '/individual': typeof IndividualRoute
  '/mare-filla': typeof MareFillaRoute
  '/matrius': typeof MatriusRoute
  '/recurs': typeof RecursRoute
  '/retir': typeof RetirRoute
  '/xerrades': typeof XerradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cures' | '/individual' | '/mare-filla' | '/matrius' | '/recurs' | '/retir' | '/xerrades'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cures' | '/individual' | '/mare-filla' | '/matrius' | '/recurs' | '/retir' | '/xerrades'
  id: '__root__' | '/' | '/cures' | '/individual' | '/mare-filla' | '/matrius' | '/recurs' | '/retir' | '/xerrades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuresRoute: typeof CuresRoute
  IndividualRoute: typeof IndividualRoute
  MareFillaRoute: typeof MareFillaRoute
  MatriusRoute: typeof MatriusRoute
  RecursRoute: typeof RecursRoute
  RetirRoute: typeof RetirRoute
  XerradesRoute: typeof XerradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recurs': {
      id: '/recurs'
      path: '/recurs'
      fullPath: '/recurs'
      preLoaderRoute: typeof RecursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xerrades': {
      id: '/xerrades'
      path: '/xerrades'
      fullPath: '/xerrades'
      preLoaderRoute: typeof XerradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mare-filla': {
      id: '/mare-filla'
      path: '/mare-filla'
      fullPath: '/mare-filla'
      preLoaderRoute: typeof MareFillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrius': {
      id: '/matrius'
      path: '/matrius'
      fullPath: '/matrius'
      preLoaderRoute: typeof MatriusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individual': {
      id: '/individual'
      path: '/individual'
      fullPath: '/individual'
      preLoaderRoute: typeof IndividualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cures': {
      id: '/cures'
      path: '/cures'
      fullPath: '/cures'
      preLoaderRoute: typeof CuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retir': {
      id: '/retir'
      path: '/retir'
      fullPath: '/retir'
      preLoaderRoute: typeof RetirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuresRoute: CuresRoute,
  IndividualRoute: IndividualRoute,
  MareFillaRoute: MareFillaRoute,
  MatriusRoute: MatriusRoute,
  RecursRoute: RecursRoute,
  RetirRoute: RetirRoute,
  XerradesRoute: XerradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
